# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"

  config.vm.define "geargencS" do |conf|
    conf.vm.hostname = "geargencS"
    conf.vm.network "private_network", ip: "192.168.56.110"
    conf.vm.network :forwarded_port, guest: 80, host: 8080
    conf.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | sh -
      sudo kubectl apply -f /vagrant/confs/deployments.yaml
      sudo kubectl apply -f /vagrant/confs/services.yaml
      sudo kubectl apply -f /vagrant/confs/ingress.yaml
    SHELL
  end

  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 4096      # RAM en Mo
    libvirt.cpus = 2           # Nombre de vCPUs
    libvirt.nested = true      # Virtualisation imbriquée
    libvirt.driver = "qemu"     # Driver (kvm par défaut)
  end

end
